sonar.projectKey=django-app
sonar.projectName=Django App
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**
